name: Snyk Code SAST Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - uses: actions/setup-node@v2
    - name: Snyk version
      run: echo "${{ steps.snyk.outputs.version }}"
    - name: Snyk Code Test
      run: snyk code test --sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}